# nixpacks.toml

[python]
# Set the required Python version
version = "3.11.4"  # Ensure this matches the Python version needed by your project

# Optional: Custom environment variables or settings
# You can specify additional environment variables if needed
[env]
  # Example: Set Poetry version explicitly (if required by your environment)
  NIXPACKS_POETRY_VERSION = "1.8.4"
  
# Optional: Additional packages or tools to install
# You can add other dependencies that your project might require
# e.g., system dependencies like build tools or database clients
[packages]
  # Uncomment to install extra dependencies if needed
  # "libpq-dev" = "latest"  # Example for installing system dependencies (PostgreSQL client)
