"""empty message

Revision ID: 059387b83437
Revises: 89da1d5005f7
Create Date: 2024-12-02 19:27:14.968745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '059387b83437'
down_revision: Union[str, None] = '89da1d5005f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floorMap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', postgresql.OID(), nullable=False),
    sa.Column('offsetX', sa.Float(), nullable=False),
    sa.Column('offsetY', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonePoint',
    sa.Column('zoneId', sa.Integer(), nullable=False),
    sa.Column('ordinalNumber', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('zoneId')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('lastSync', sa.DateTime(), nullable=False),
    sa.Column('floorMapId', sa.Integer(), nullable=False),
    sa.Column('active', postgresql.BIT(length=1), nullable=False),
    sa.ForeignKeyConstraint(['floorMapId'], ['floorMap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('floorMapId', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floorMapId'], ['floorMap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assetPositionHistory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('floorMapId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['floorMapId'], ['floorMap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assetZoneHistory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('zoneId', sa.Integer(), nullable=False),
    sa.Column('enterDateTime', sa.DateTime(), nullable=False),
    sa.Column('exitDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['zoneId'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'users', 'userRole', ['roleId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('assetZoneHistory')
    op.drop_table('assetPositionHistory')
    op.drop_table('zone')
    op.drop_table('asset')
    op.drop_table('zonePoint')
    op.drop_table('userRole')
    op.drop_table('floorMap')
    # ### end Alembic commands ###
