"""empty message

Revision ID: 65af5b6dcfe5
Revises: 7b694012ac68
Create Date: 2024-12-10 23:57:49.720795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65af5b6dcfe5'
down_revision: Union[str, None] = '7b694012ac68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floorMap', sa.Column('tx', sa.Float(), nullable=False))
    op.add_column('floorMap', sa.Column('ty', sa.Float(), nullable=False))
    op.add_column('floorMap', sa.Column('tw', sa.Float(), nullable=False))
    op.add_column('floorMap', sa.Column('th', sa.Float(), nullable=False))
    op.drop_column('floorMap', 'offsetY')
    op.drop_column('floorMap', 'offsetX')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floorMap', sa.Column('offsetX', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('floorMap', sa.Column('offsetY', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('floorMap', 'th')
    op.drop_column('floorMap', 'tw')
    op.drop_column('floorMap', 'ty')
    op.drop_column('floorMap', 'tx')
    # ### end Alembic commands ###
