"""empty message

Revision ID: 8d795357a292
Revises: 2e5e21568e1d
Create Date: 2024-12-20 17:55:44.066289

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d795357a292"
down_revision: Union[str, None] = "2e5e21568e1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assetPositionHistory",
        "dateTime",
        new_column_name="timestamp",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assetPositionHistory",
        "timestamp",
        new_column_name="dateTime",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    # ### end Alembic commands ###
