"""empty message

Revision ID: 9fe38fc83054
Revises: 92deb4e81060
Create Date: 2024-12-05 21:19:14.079686

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fe38fc83054"
down_revision: Union[str, None] = "92deb4e81060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="password::bytea",
    )
    op.alter_column(
        "users",
        "salt",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="salt::bytea",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "salt",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
